[package]
name = "fetter"
version = "0.1.0"
authors = ["Harry Wolff <hello@harrywolff.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
